spring:
  # application-OOOOO.yml 에서 작동 환경을 불러온다.
  profiles:
    active: heroku

  # DataSource
  datasource:
    type: ${props.spring.datasource.type}
    driver-class-name: ${props.spring.datasource.driver-class-name}
    url: ${props.spring.datasource.url}
    username: ${props.spring.datasource.username}
    password: ${props.spring.datasource.password}

  # JPA
  jpa:
    hibernate:
      ddl-auto: ${props.spring.jpa.hibernate.ddl-auto}
    generate-ddl: ${props.spring.jpa.generate-ddl}
    show-sql: ${props.spring.jpa.show-sql}
    database-platform: ${props.spring.jpa.database-platform}
    properties:
      hibernate.format_sql: ${props.spring.jpa.properties.hibernate.format_sql}

  # Redis 연동 (URL 은 Lettuce 에서 비밀번호 필드를 인식하지 않는다 하더라.)
  redis:
    host: ${props.spring.redis.host}
    port: ${props.spring.redis.port}
    username: ${props.spring.redis.username}
    password: ${props.spring.redis.password}
    url: ${props.spring.redis.url}

server:
  port: ${props.server.port}
  servlet:
    context-path: ${props.server.servlet.context-path}