### local 프로필 환경 설정
props:
  spring:
    # DataSource
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pb-board?useUnicode=true&characterEncoding=utf8
      username: kangdev9401
      password: 1q2w3e4r5t^

    # JPA
    jpa:
      hibernate:
        ddl-auto: create-drop
      generate-ddl: true
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
      properties:
        hibernate.format_sql: false

    # Redis 연동
    redis:
      host: localhost
      port: 6379
      password:

  # 서블릿 작동 환경 설정
  server:
    port: 8081
    servlet:
      context-path: /pb-board