spring:
  # application-OOOOO.yml 에서 작동 환경을 불러온다.
  profiles:
    active: local

  # DataSource
  datasource:
    type: ${props.spring.datasource.type}
    driver-class-name: ${props.spring.datasource.driver-class-name}
    url: ${props.spring.datasource.url}
    username: ${props.spring.datasource.username}
    password: ${props.spring.datasource.password}

  # H2
  h2:
    console:
      enabled: ${props.spring.h2.console.enabled}
      path: ${props.spring.h2.console.path}

  # JPA
  jpa:
    hibernate:
      ddl-auto: ${props.spring.jpa.hibernate.ddl-auto}
    generate-ddl: ${props.spring.jpa.generate-ddl}
    show-sql: ${props.spring.jpa.show-sql}
    database-platform: ${props.spring.jpa.database-platform}
    properties:
      hibernate.format_sql: ${props.spring.jpa.properties.hibernate.format_sql}

  # Redis 연동
  redis:
    host: ${props.spring.redis.host}
    port: ${props.spring.redis.port}
    password: ${props.spring.redis.password}

server:
  port: ${props.server.port}
  servlet:
    context-path: ${props.server.servlet.context-path}